Providing access to the player's LoginResult on LoginEvent
PaperMC/Waterfall pull request #159
Opened 2017-07-21 19:01 UTC by phenomax

Adds the feature requested in #154

2017-07-24 20:27 UTC, Janmm14 commented
I suggest to remove unneeded import order changing and possibly to not change imports at all but use fully qualified class names for mich easier patch compatibility to upstream changes.

2017-07-24 20:30 UTC, phenomax commented
Do you think deleting unused will have so much impact? I didnt do that intentionally. It's just part of IntelliJ's clean up

2017-07-24 20:31 UTC, jamierocks commented
Don't remove unused, only add imports.
It ensures that the patches can be merged easily.

2017-07-24 20:31 UTC, jamierocks requested changes
forgot that these need to be submitted -_-

2017-07-24 20:31 UTC, jamierocks commented on BungeeCord-Patches/0044-Providing-access-to-the-player-s-LoginResult-on-Logi.patch
> +-import java.math.BigInteger;
Please resolve these moved imports.

2017-07-24 20:31 UTC, jamierocks commented on BungeeCord-Patches/0044-Providing-access-to-the-player-s-LoginResult-on-Logi.patch
> +-    public LoginEvent(PendingConnection connection, Callback<LoginEvent> done)
There is going to need to be a constructor with the original signature.

2017-07-25 12:41 UTC, phenomax commented
Thanks for reviewing! I'll apply the changes asap

2017-07-25 20:05 UTC, phenomax commented on BungeeCord-Patches/0044-Providing-access-to-the-player-s-LoginResult-on-Logi.patch
> +-import java.math.BigInteger;
Do you have any tip to disable IntelliJ's auto import moving?

2017-07-25 20:07 UTC, jamierocks commented on BungeeCord-Patches/0044-Providing-access-to-the-player-s-LoginResult-on-Logi.patch
> +-import java.math.BigInteger;
ye `Preferences`->Search for Imports->Disable the option

2017-07-26 21:39 UTC, closed without merging

2017-07-26 21:41 UTC, jamierocks commented
Okay then.

2017-07-26 21:55 UTC, phenomax commented
I hate it,, when there are tons of revers in the commit history. So I ll start this PR from scratch in the next days.
@jamierocks Dont worry ^^

2017-07-26 21:58 UTC, jamierocks commented
Thats no issue, the commits can be squashed - but whatever I guess.