Add exception reporting event
PaperMC/Waterfall pull request #488
Opened 2020-04-22 05:50 UTC by theminecoder

Since bungeecord has gone and made the plugin manager a final class (which is a good thing in some regards) there is no way to wrap around it to handle exception catching for commands and events.

This patch copies over the exception event (and corresponding exception classes) that exists in paper today and implements it in the places around the proxy codebase that should fire the event.

Couple of notes:
- Bungee's EventBus registration doesn't ever store a reference to the plugin that registered the listener so that exception wrapper doesn't have a plugin associated with it. (not quite something I was happy to play with on my own)
- `ProxyInternalException` & `ProxyPluginMessageException` aren't currently used anywhere but were left in the pr in case something needs to use them that I am unaware of.

2020-04-22 12:36 UTC, Janmm14 commented
We need something that prevents stackoverflow: if an error happens during event handling of any event and if there is a faulty plugin always throwing in ProxyExceptionEvent this creates unneccessary long console output and cpu usage. This could be achieved by having a separate, private callEvent method which requires a ProxyExceptionEvent and which gives the eventbus an empty exception handler.

2020-04-22 14:29 UTC, theminecoder commented
> We need something that prevents stackoverflow: if an error happens during event handling of any event and if there is a faulty plugin always throwing in ProxyExceptionEvent this creates unneccessary long console output and cpu usage.
> 
> 
> 
> This could be achieved by having a separate, private callExceptionEvent method which requires a ProxyExceptionEvent and which gives the eventbus an empty exception handler and which is called instead of callEvent for ProxyExceptionEvents.

There is already a bailout check in the error handler that will return if we are handling a execution event, preventing the stackoverflow. 

https://github.com/PaperMC/Waterfall/pull/488/files#diff-10c042e7d4737de4aeaf80dc1fb8c89fR541

2020-05-02 18:07 UTC, MrIvanPlays commented
I was the one who made the PluginManager final. This was intentional to stop people from modifying it at runtime. Also I don't find a usecase about your pr; exceptions occurring in event handling or command handling should be handled there. A direct example is enforcing an specific argument type for command:

```java
public void execute(CommandSender sender, String[] args) {
   // ...
  try {
      Integer.parseInt(args[0]);
  } catch (NumberFormatException e) {
      sender.sendMessage(new ComponentBuilder("First argument should be number!").setColor(ChatColor.RED).build());
      return;
  }

  int firstArgument = Integer.parseInt(args[0]);
  // ...
}
```

For other things such as enabling/disabling/loading plugins on-the-fly it would be better to have a PR here or to upstream adding such feature to the api and not using hacks.

2020-05-02 18:23 UTC, electronicboy requested changes
Looks fine, only real thing is the waterfall comments, they should annotate the set of changes, I'd suggest glancing over the paper contribution guide if you haven't

2020-05-03 08:58 UTC, theminecoder commented
Think I got everything with comments now. Let me know if I missed anything

2020-05-03 09:07 UTC, theminecoder commented
@MrIvanPlays I understand why you made it final. Honestly I think it's a good thing in the long run. However there is a use case to having exceptions being available like this - which is actually what this pr is about.

I make and use a plugin that grabs all of the exceptions from proxies and backend servers and forwards them to sentry so I can proactively keep an eye on issues without having to tail x amount of logs for all the servers that I run. Has been a lifesaver numerous amounts of time.

Until this pr is merged the only way to do this on bungee and waterfall is to proxy the plugin manager and even that doesn't get you access to scheduled tasks, so having the events allows me to monitor everything without hacky access to the server internals.

2020-05-03 11:14 UTC, MrIvanPlays commented
> @MrIvanPlays I understand why you made it final. Honestly I think it's a good thing in the long run. However there is a use case to having exceptions being available like this - which is actually what this pr is about.
> 
> I make and use a plugin that grabs all of the exceptions from proxies and backend servers and forwards them to sentry so I can proactively keep an eye on issues without having to tail x amount of logs for all the servers that I run. Has been a lifesaver numerous amounts of time.
> 
> Until this pr is merged the only way to do this on bungee and waterfall is to proxy the plugin manager and even that doesn't get you access to scheduled tasks, so having the events allows me to monitor everything without hacky access to the server internals.

I don't really understand what you're trying to achieve here. You want to collect all the exceptions in one place, no? Well, if thats the case then good idea for adding these events, however I still think that occurring exceptions should be handled in the source (command, event handling) and not to be suppressed in a event.

2020-05-03 12:27 UTC, lucko commented
> however I still think that occurring exceptions should be handled in the source (command, event handling) and not to be suppressed in a event.

Nobody is making the argument that they shouldn't?

Exception **handling** clearly isn't the use-case of the PR. Read the title: "exception **reporting**".

The exceptions are not being suppressed, they're just being exposed in an event as well as in a call to the proxy logger.

2020-05-07 14:32 UTC, electronicboy approved these changes

2020-05-07 14:32 UTC, merged