Update Waterfall API JavaDocs Link
PaperMC/Waterfall pull request #657
Opened 2021-06-12 17:09 UTC by KolakZ

2021-06-12 17:25 UTC, Janmm14 requested changes

2021-06-12 17:25 UTC, Janmm14 commented on README.md
> + * Waterfall API JavaDocs here: [papermc.io/javadocs/waterfall](https://papermc.io/javadocs/waterfall/1.16)
```suggestion
 * Waterfall API JavaDocs here: [papermc.io/javadocs/waterfall](https://papermc.io/javadocs/waterfall/1.17)
```

2021-06-12 17:29 UTC, KolakZ commented on README.md
> + * Waterfall API JavaDocs here: [papermc.io/javadocs/waterfall](https://papermc.io/javadocs/waterfall/1.16)
Whoops, sorry about that xD

2021-06-12 17:35 UTC, KolakZ reviewed
Didn't catch that, thanks!

2024-04-02 17:22 UTC, electronicboy commented
Thanks for the PR, however this generally got neglected due to my health

2024-04-02 17:22 UTC, closed without merging