Fix rare potion race condition with forge clients
PaperMC/Waterfall pull request #73
Opened 2016-08-18 18:30 UTC by Aaron1011

Tl;dr: This PR fixes a rare race condition which causes Forge clients to crash when switching between servers.

**Background**

When a Forge client connects to a Forge server, the client and server perform a special handshake before continuing with the login process. During this handshake, the server and client exchange their respective mod lists (disconnecting if a mod is missing on either ide). They also exchange [registry information](https://github.com/MinecraftForge/MinecraftForge/blob/6e90348/src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeClientState.java#L105), which includes blocks, items, and potions.

Normally, this handshake is performed only once - when a player initially connects to a server (e.g. opening a singleplayer world, or connceting to a server from the 'Multiplayer' screen). However, with Waterfall/Bungeecord, players can switch between different Forge servers, each having distinct mod lists and registry data. To facilitate this, Forge allows a [special reset packet](https://github.com/MinecraftForge/MinecraftForge/blob/6e90348/src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeClientState.java#L159) to be sent. This resets the handshake process toits initial state, allowing it to be re-performed by the server the player is switching to. Accordingly, Waterfall/Bungeecord [sends this packet](https://github.com/SpigotMC/BungeeCord/blob/aaddc9fcfdcada8d19ab115f2dcc8aed413a9206/proxy/src/main/java/net/md_5/bungee/forge/ForgeClientHandler.java#L91) when switching a Forge client to a Forge server.

However, there is a critical difference between the intiial handshake performed when a client first joins, and any handshakes performed after a reset packet is sent. The former handshakes take place right at the start of the connetion, becfore the client has joined the world. Because of this, `WorldClient` has not been instantiated yet, and thus cannot interact with the registry (more on this later). Any handshakes initiated by reset packets, however, are performed while the player is still in the world! This has the advantage of allowing the player to be rejected by the target server (if the client is missing a required mod of the new server, for example), without the need to first respawn them or switch their dimension (as is done during an actual successful transfer). However, this means that while the handshake is taking place, the client world is still running and ticking. This leads to the issue described below.

**The issue**

Because the secondary handshake is happening in parallel (specifically, on a Netty thread) with the main game execution (on the main thread), race conditions have the potential to occur. Fortunately, while the handshaking process can cause some temporary odd behavior (the player falling through the ground while the block registry is being rebuild), it doesn't result in crashes - with one notable exception.

When the client starts to load registry data from the server, it first [clears out the `Potion.potionTypes`](https://github.com/MinecraftForge/MinecraftForge/blob/6e90348dc546164b21735aefd83ed0bac0d8283c/src/main/java/net/minecraftforge/fml/common/registry/PersistentRegistryManager.java#L156) array. Normally, this is fine, since the client world doesn't yet exist. However, during a reset-triggered handshake, the client world is still ticking entities - importantly, entity potion effects. If the client happens to tick an entity after `Potion.potionTypes` is cleared out, but before it's filled back in with data from the server, the client will crash:

```
java.lang.NullPointerException: Ticking entity
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:113)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:517)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:300)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:279)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1564)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

The following code snippet, from `PotionEffect#onUpdate`, shows why:

```
if (Potion.potionTypes[this.potionID].isReady(this.duration, this.amplifier))
```

When the race condition occurs, all elements in `Potion.potionTypes` will be null, causing an NPE. This happens very infrequently, since there's only a small window of time - specifically, while [PersistentRegistryManager.injectSnapshot](https://github.com/MinecraftForge/MinecraftForge/blob/6e90348dc546164b21735aefd83ed0bac0d8283c/src/main/java/net/minecraftforge/fml/common/registry/PersistentRegistryManager.java#L143) - during which ticking an entity's potion effect will cause the crash.

**Reproducing**

Since this is a race condition, it can be difficult to reproduce through normal means. The best way to reproduce it is through a breakpoint in an IDE. Done correctly, this can reproduce the issue 100% of the time.

Steps to reproduce:

1. Setup a Waterfall/Bungeecord instance, with two forge servers connected to it.
2. Start a Forge 1.8.9 client with a debugger connected. This can be done through the `GradleStart` class in a forge mod workspace, or by specifying the necessary arguments in the profile settings of your minecraft client.
3. Give yourself, or any entity on the server, any potion effect (preferrably with a long duration, so that it won't expire while you're trying to switch servers).
4. Set a breakpoint on [this line of PersistentRegistryManager](https://github.com/MinecraftForge/MinecraftForge/blob/1.8.9/src/main/java/net/minecraftforge/fml/common/registry/PersistentRegistryManager.java#L159) in your IDE. **IMPORTANT**: This breakpoint *must* be set to only suspend the thread it's in, rather than all threads. This simulates an arbitrarily long execution time of that method (as well as the Netty thread that it's called from).
5. Attempt to connect to the other Forge server in the network. The client should crash almost immediately, provided that the breekpoint is set correctly.

**The fix**

Fixing this issue turns out to be farily simple. It consists of two parts:

* Removing all potion effects from the client's world (on all entities) before performing the handshake
* Supressing any new potion packets sent during the handshake
 
The first part is accomplished by keeping track of all potion effects on a client. This is done by listening for `Entity Effect` and `Remove Entity Effect` packets, and adding/removing mappings from entity ids to potion ids as necessasry. When the client switches to a Forge server, `Remove Entity Effect` packets are sent to the client for each mapping stored. Since this is done before the handshake packet is even sent, it guarantees that no potions are present on the client when the handshake begins.

The second part is accomplished by blocking all potion packets sent from the server while the handshake is in process. During testing, it was discovered that the first part alone was  [...]

2016-08-18 18:39 UTC, Zachincool commented
Yes this crash is quite frustrating. Many of my players experience it on my 1.8.9 Pixelmon server. For servers still running 1.8.9 (which is many), this is a problem.

2016-08-18 19:23 UTC, jamierocks commented on BungeeCord-Patches/0042-Fix-potion-race-condition-on-forge.patch
> ++import java.util.logging.Level;
This annoys me also, but could you undo this formatting change?

2016-08-18 19:28 UTC, jamierocks commented
Unfortunately bungee hasn't got the nicest formatting but also unfortunately we are forced to go by them as so that we don't have a huge number of merge conflicts. Thankfully this is remedied by the small number of commits to bungee, and minimalistic patches we have.

2016-08-18 23:52 UTC, Techcable commented on BungeeCord-Patches/0042-Fix-potion-race-condition-on-forge.patch
> +Subject: [PATCH] Fix potion race condition on forge
Please note in the patch text this only occurs in 1.8.9, so we can easily move it to travertine once upstream drops 1.8.9 support.

2016-09-14 09:48 UTC, jamierocks commented
@Aaron1011 whats the status of this pr?

2016-09-14 21:04 UTC, Techcable approved these changes
Aside from minor formatting issues, this seems good.

2016-09-14 21:06 UTC, Techcable commented
I'll fix the formatting and merge this if there are no objections.

2016-09-14 21:07 UTC, jamierocks commented
Actually Aaron said he would be finished it up today ;)

2016-09-14 21:11 UTC, Techcable commented
Oh wait, it's not finished?

2016-09-14 21:12 UTC, jamierocks commented
Well fixing up all your comments.

2016-09-15 20:30 UTC, Aaron1011 commented
@fuzzybot @jamierocks: Ok, the formatting should be all cleaned up. Let me know if I need to make any more changes.

2016-09-15 20:32 UTC, jamierocks commented on BungeeCord-Patches/0041-Fix-potion-race-condition-on-forge.patch
> +Subject: [PATCH] Fix potion race condition on forge
Fix potion race condition on Forge clients
For 1.8.9.

2016-09-15 20:32 UTC, jamierocks commented on BungeeCord-Patches/0041-Fix-potion-race-condition-on-forge.patch
> ++            // Waterfall start
Waterfall end

2016-09-15 20:37 UTC, jamierocks requested changes
Looks good. 👍

2016-09-15 20:41 UTC, jamierocks approved these changes
👍

2016-09-15 20:43 UTC, merged

2016-09-18 05:57 UTC, Zachincool commented
Thanks for the work